"""empty message

Revision ID: c4c7b2d9819b
Revises: 
Create Date: 2022-05-04 11:11:25.626622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4c7b2d9819b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('tourbooking', 'tourbooking_amount',
    #            existing_type=mysql.FLOAT(),
    #            nullable=False)
    pass
    # op.alter_column('tourpackage_payment', 'tourpackage_payment_date',
    #            existing_type=mysql.DATETIME(),
    #            nullable=True,
    #            existing_server_default=sa.text('current_timestamp()'))
    # # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tourpackage_payment', 'tourpackage_payment_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('tourbooking', 'tourbooking_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
